TARGET=band_req_mc
SOURCES=band_req_mc.c 

# <Num Requests> <Num Elements in Array> <Num Iterations>
NUM_CORES=2
NUM_REQS=16
APP_FLAGS ?=$(NUM_CORES) $(NUM_REQS) 50100 718203


include ../common/Makefile.tests
