#!/usr/bin/env bash

#/home/centos/firesim/sim/generated-src/f1/FireSimNoNIC-FireSimRocketChipConfig-FireSimConfig/VFireSimNoNIC +permissive +mm_relaxFunctionalModel=0 +mm_openPagePolicy=1 +mm_backendLatency=2 +mm_schedulerWindowSize=8 +mm_transactionQueueDepth=8 +mm_dramTimings_tAL=0 +mm_dramTimings_tCAS=14 +mm_dramTimings_tCMD=1 +mm_dramTimings_tCWD=10 +mm_dramTimings_tCCD=4 +mm_dramTimings_tFAW=25 +mm_dramTimings_tRAS=33 +mm_dramTimings_tREFI=7800 +mm_dramTimings_tRC=47 +mm_dramTimings_tRCD=14 +mm_dramTimings_tRFC=160 +mm_dramTimings_tRRD=8 +mm_dramTimings_tRP=14 +mm_dramTimings_tRTP=8 +mm_dramTimings_tRTRS=2 +mm_dramTimings_tWR=15 +mm_dramTimings_tWTR=8 +mm_rowAddr_offset=18 +mm_rowAddr_mask=65535 +mm_rankAddr_offset=16 +mm_rankAddr_mask=3 +mm_bankAddr_offset=13 +mm_bankAddr_mask=7 +slotid=0 +niclog0=niclog +linklatency0=6405 +netbw0=100 +netburst0=8 +nic-loopback0 +dramsim +max-cycles=100000000 +permissive-off pk2 ${@:2} 2> stuff


#/home/centos/firesim/sim/generated-src/f1/FireSimNoNIC-FireSimRocketChipConfig-FireSimConfig/VFireSimNoNIC +permissive +sample=/home/centos/firesim/sim/output/f1/FireSimNoNIC-FireSimRocketChipConfig-FireSimConfig/rv64um-v-mul.sample  +mm_relaxFunctionalModel=0 +mm_writeMaxReqs=16 +mm_readMaxReqs=16 +mm_writeLatency=30 +mm_readLatency=30 +slotid=0 +niclog0=niclog +linklatency0=6405 +netbw0=100 +netburst0=8 +nic-loopback0 +dramsim +max-cycles=100000000  +permissive-off pk2 ${@:2} 2> stuff

echo "$@"

#/home/centos/firesim/sim/output/f1/FireSimNoNIC-FireSimRocketChipConfig-FireSimConfig/rv64um-v-mul 

