TARGET=mem_interleaving
SOURCES=mem_interleaving.c 

# <Num Requests> <Num Elements in Page> <Num Iterations>
NUM_REQUESTS=2
NUM_ITERATIONS=10
PAGE_SZ=8
APP_FLAGS ?=$(NUM_REQUESTS) $(PAGE_SZ) $(NUM_ITERATIONS)


include ../common/Makefile.tests
