# This Makefile is included by the subproject ukernels.

SHELL 	 :=/bin/bash
APP_FLAGS ?=
SOURCES 	 += ../common/cctimer.c ../common/barrier.c ../common/cclfsr.c

OBJECTS ?= $(patsubst %.cpp,%.o,$(patsubst %.c,%.o,$(patsubst %.cc,%.o,$(SOURCES) ) ) )



# customize the build based on the architecture
#
#include ../arch/$(ARCH)/Makefile.mk

ifeq ($(ARCH),riscv)
	include ../arch/riscv/Makefile.mk
else ifeq ($(ARCH),tile64)
	include ../arch/tile64/Makefile.mk
else ifeq ($(ARCH),x86)
	include ../arch/x86/Makefile.mk
else ifeq ($(ARCH),arm)
	include ../arch/arm/Makefile.mk
else
	include ../arch/generic/Makefile.mk
endif


# Build targets
all: $(TARGET)

$(TARGET): $(OBJECTS)
	if $(foreach source,$(OBJECTS),[ $(source) -nt $(TARGET) ] ||) 1; \
	then $(CC) $(CFLAGS) $^ -o $@ $(LD_FLAGS) $(LD_LIBS); \
	fi

run: $(TARGET)
	./$(TARGET) $(APP_FLAGS)


clean:
	-rm -f *.o *.d ../common/*.o $(TARGET)

